Tictactoe
teekaytech/tictactoe pull request #1
Opened 2020-09-04 15:15 UTC by rida-elbahtouri

## In this branch we :
- Created the HTML side of the game Tic-Tac-Toe
- build the logic using javascript
- made the players capable of restart matches

2020-09-04 15:59 UTC, stratospherique requested changes
### Great start @rida-elbahtouri :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

#### Behaviour (required) :warning: 
* [x] It's impossible to restart a game after a draw. The restart message keeps popping after clicking a cell  in the board.
- I noticed some spelling errors in the messages displayed. kindly fix them

#### General (required) :warning: 
* [x] No `console.log` commited to repo. It's ugly, it kills performance. and it can make confidential data be visible in the browser tools. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/console_log_requirement.png) from Pathwright)
* [ ] ES6 - using object destructuring to get the values from an object. This way you can avoid repeating a lot of code. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/destructuring_requirement.png) from Pathwright)
* [x] Keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)
* [ ] Keep all the styling logic in CSS files (If you need to change something like a background image, add the classes with the different backgrounds to the CSS and then change the class name attribute with JavaScript) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/styling_requirement.png) from Pathwright)
#### Implementation (required) :warning: 
* [x] It doesn't use `global` code - encapsulate logic inside modules or factories ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/global_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript))
* [ ] It has a function with the only responsibility of rendering the contents of the gameboard array to the webpage ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/render_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript))
- Keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)
### That's it :relaxed: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-09-07 12:19 UTC, whiz25 requested changes
## Changes Required :pray:
Nice work implementing changes required by the previous reviewer. There is however, a few things we need to fix. There is still logic concerning the DOM in the main.js file. Please separate the view logic from the JS logic.

### Martin Afani

2020-09-07 12:19 UTC, whiz25 commented on main.js
> +        if (cell.innerHTML.length == 0) {
- any piece of code related to the view (DOM) should not be here. You need to move this code into the dom.js file. This was already pointed out in the previous review.

2020-09-07 12:19 UTC, whiz25 commented on main.js
> +  movehtml.style.padding = "10px";
- this should be in the DOM file. This file should only contain pure JS and nothing more

2020-09-07 12:56 UTC, rida-elbahtouri commented
### Note:
I couldn't move the validateMove function to dom.js, because it depends on variables that exist in the main.js file, and If I pass them as parameters that will cause problems with the logic, the game will refuse to restart

2020-09-07 13:15 UTC, whiz25 approved these changes
## Approved :clap: 
Merge and proceed to the next milestone.

### Martin Afani

2020-09-07 16:16 UTC, merged